# Generated by Django 3.0.8 on 2021-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0002_anime_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DRAMA', 'DRAMA'), ('ROMANCE', 'ROMANCE'), ('ACTION', 'ACTION'), ('SUPERPOWER', 'SUPERPOWER')], max_length=200)),
                ('episode', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
