# Generated by Django 3.0.8 on 2021-03-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0003_auto_20210308_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animewatch',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myanime.Anime'),
        ),
    ]
