# Generated by Django 3.0.8 on 2021-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0005_auto_20210308_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animewatch',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
