# Generated by Django 3.0.8 on 2021-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0007_auto_20210309_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
