# Generated by Django 3.0.8 on 2021-03-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0009_auto_20210309_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myanime.Season'),
        ),
    ]
