# Generated by Django 3.0.8 on 2021-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0014_auto_20210310_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'episode_id')},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='category',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
    ]
