# Generated by Django 3.0.8 on 2021-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0015_auto_20210310_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecategory',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Martial', 'Martial Arts'), ('Mystery', 'Mystery'), ('Super', 'Super Power'), ('Supernatural', 'Supernatural')], max_length=200),
        ),
    ]
