# Generated by Django 3.0.8 on 2021-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0016_auto_20210311_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='category',
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='myanime.AnimeCategory'),
        ),
    ]
