# Generated by Django 3.0.8 on 2021-03-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myanime', '0018_auto_20210311_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='link',
            new_name='url',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myanime.Episode')),
            ],
        ),
    ]
